---
- name: RMAN Backup Oracle Enterprise
  hosts: all
  gather_facts: no

  become: yes
  become_method: sudo
  become_user: oracle

  serial: 2

  vars:
    base_dir: /mnt/oracle_FLZ001/oracle/prd
    backup_type: "{{ tipo_backup }}"

  tasks:

    - name: Validar instâncias
      fail:
        msg: "oracle_instances não definido"
      when: oracle_instances is not defined

    - name: Executar backup por instância
      include_tasks: tasks/rman_instance.yml
      loop: "{{ oracle_instances }}"
      loop_control:
        loop_var: db
