- name: Gerar dashboard fake RMAN
  hosts: localhost
  gather_facts: no

  tasks:

    - name: Criar diretório web (AWX safe)
      file:
        path: /tmp/awx_reports
        state: directory
        mode: '0755'

    - name: Gerar HTML fake
      copy:
        dest: /tmp/awx_reports/rel_backups.html
        content: |
          <html>
          <head><title>RMAN Dashboard</title></head>
          <body>
            <h2>RMAN Dashboard (AWX TESTE)</h2>
            <table border="1">
              <tr><th>Host</th><th>SID</th><th>Status</th></tr>
              <tr><td>db01</td><td>CT1PRD</td><td style="color:green">SUCCESS</td></tr>
              <tr><td>db01</td><td>CT10PRD</td><td style="color:green">SUCCESS</td></tr>
              <tr><td>db02</td><td>OIPRD</td><td style="color:red">FAILED</td></tr>
            </table>
          </body>
          </html>
