- name: Oracle RMAN Enterprise Backup
  hosts: all
  gather_facts: no

  become: yes
  become_user: oracle

  vars:
    backup_type: "{{ tipo_backup }}"

  tasks:

    - name: Executar backup por instância
      include_tasks: tasks/rman_instance.yml
      loop: "{{ oracle_instances }}"
      loop_control:
        loop_var: oracle_db
