---
- name: Oracle RMAN Enterprise Backup
  hosts: all

  gather_facts: no

  become: yes
  become_method: sudo
  become_user: oradb01

  vars:
    backup_type: "{{ tipo_backup }}"

  tasks:

    - include_tasks: tasks/rman_instance_tunicprd.yml
